version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=qustkdcjf
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306


  php:
    image: php:8-fpm
    # image: anti1346/php-fpm-laravel:8.1
    # build:
    #   context: ./php-fpm/
    #   dockerfile: Dockerfile
    restart: unless-stopped
    container_name: php
    depends_on:
      - mariadb
    volumes:
      - ./webroot:/usr/share/nginx/html
    ports:
      - 9000:9000


  nginx:
    image: anti1346/nginx:1.21.6
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./webroot:/usr/share/nginx/html
    depends_on:
      - php
    ports:
      - 80:80
      - 443:443
