version: '3.7'
services:

  nginx:
    image: anti1346/nginx:1.21.6
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./webroot:/var/www/html
    depends_on:
      - myapp
    ports:
      - 80:80
      - 443:443
    networks:
      - myapp-net


  myapp:
    image: anti1346/php-fpm-laravel:8.1
    build:
      context: ./php-fpm/
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: myapp
    user: root
    volumes:
      - ./webroot:/var/www/html
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    networks:
      - myapp-net


  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    container_name: mariadb
    env_file: ./mariadb/.env
    environment:
      - MYSQL_ROOT_PASSWORD=qustkdcjf
    volumes:
      - ./mariadb/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - myapp-net

networks:
  myapp-net:
