version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=qustkdcjf
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306


  php:
    image: anti1346/php-fpm-laravel:8.1
    build:
      context: .
    restart: unless-stopped
    container_name: php
    depends_on:
      - mariadb
    volumes:
      - ./webroot/html:/var/www/html
    ports:
      - 9000:9000


  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./webroot/html:/var/www/html
    depends_on:
      - php
    ports:
      - 80:80
      - 443:443
